# Form implementation generated from reading ui file 'votingApp1.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 748)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.idInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.idInput.setGeometry(QtCore.QRect(180, 70, 121, 21))
        self.idInput.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.idInput.setObjectName("idInput")
        self.janeRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.janeRadio.setGeometry(QtCore.QRect(180, 140, 100, 20))
        self.janeRadio.setStyleSheet("color: rgb(0, 0, 0);")
        self.janeRadio.setObjectName("janeRadio")
        self.johnRadio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.johnRadio.setGeometry(QtCore.QRect(180, 170, 100, 20))
        self.johnRadio.setStyleSheet("color: rgb(0, 0, 0);")
        self.johnRadio.setObjectName("johnRadio")
        self.submitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(120, 200, 201, 32))
        self.submitButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.submitButton.setObjectName("submitButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 70, 21, 16))
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 110, 101, 16))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.messageLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.messageLabel.setGeometry(QtCore.QRect(150, 240, 141, 16))
        self.messageLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.messageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.messageLabel.setObjectName("messageLabel")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 401, 271))
        self.label_4.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 30, 141, 20))
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_4.raise_()
        self.idInput.raise_()
        self.janeRadio.raise_()
        self.johnRadio.raise_()
        self.submitButton.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.messageLabel.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.janeRadio.setText(_translate("MainWindow", "Jane"))
        self.johnRadio.setText(_translate("MainWindow", "John"))
        self.submitButton.setText(_translate("MainWindow", "Submit Vote"))
        self.label.setText(_translate("MainWindow", "ID"))
        self.label_2.setText(_translate("MainWindow", "CANDIDATES"))
        self.messageLabel.setText(_translate("MainWindow", "Text"))
        self.label_5.setText(_translate("MainWindow", "VOTING APPLICATION"))
